### ISSUE TITLE
awsenv should download aws tools rather than including in repository.

### ISSUE THREAD

**Issue by miah** [michaelcontento/awsenv#7]
Many security related arguments can be made here, why not just have a argument that downloads and installs the cli tools into your .awsenv?

awsenv looks promising otherwise! =)

-Miah

**Comment by michaelcontento** [comment]
Wow! 3 years later .. sorry about that :blush: 

But thanks to @ches this is fixed with https://github.com/michaelcontento/awsenv/pull/15
